# action.yml

name: 'Terraform Apply'
description: 'Apply local terraform'
inputs:

  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/denkoren/actions-experiments/terraform:latest'
  entrypoint: '/action.sh'
  args:
    - -help
