name: Apply terraform

on:
  workflow_dispatch: {}

jobs:
  apply-terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: denkoren/actions-experiments/actions/terraform@v1
